---
apiVersion: v1
kind: Service
metadata:
  name: k8-fullstack-helloworld-client
spec:
  selector:
    app: k8-fullstack-helloworld
  ports:
    - port: 3000
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: k8-fullstack-helloworld-api
spec:
  selector:
    app: k8-fullstack-helloworld
  ports:
    - port: 5000
      targetPort: 80
  type: LoadBalancer
